$('.brand-carousel').owlCarousel({
    loop:true,
    margin:10,
    autoplay:true,
    autoplayTimeout:2000,
    responsive:{
      0:{
        items:1
      },
      600:{
        items:3
      },
      1000:{
        items:5
      }
    }
  }) 
  
  $(document).ready(function(){
    $('.readmore').click(function(){
      $('.hidden-text').fadeIn(500);
    })
  })
  $(document).ready(function(){
    $('.readmore').click(function(){
      $(this).hide();
    })
  })
  $(document).ready(function(){
    $('.readmore').click(function(){
      $('.readless').fadeIn(500);
    })
  })
  $(document).ready(function(){
    $('.readless').click(function(){
      $('.readmore').fadeIn(500);
    })
  })
  $(document).ready(function(){
    $('.readless').click(function(){
      $('.hidden-text').hide();
    })
  })
  $(document).ready(function(){
    $('.readless').click(function(){
      $(this).hide();
    })
  })
  
  $(document).ready(function(){
    $('.readmore1').click(function(){
      $('.hidden-text1').fadeIn(500);
    })
  })
  $(document).ready(function(){
    $('.readmore1').click(function(){
      $(this).hide();
    })
  })
  $(document).ready(function(){
    $('.readmore1').click(function(){
      $('.readless1').fadeIn(500);
    })
  })
  $(document).ready(function(){
    $('.readless1').click(function(){
      $('.readmore1').fadeIn(500);
    })
  })
  $(document).ready(function(){
    $('.readless1').click(function(){
      $('.hidden-text1').hide();
    })
  })
  $(document).ready(function(){
    $('.readless1').click(function(){
      $(this).hide();
    })
  })
 
 
  $(document).ready(function(){
    $('.readmore2').click(function(){
      $('.hidden-text2').fadeIn(500);
    })
  })
  $(document).ready(function(){
    $('.readmore2').click(function(){
      $(this).hide();
    })
  })
  $(document).ready(function(){
    $('.readmore2').click(function(){
      $('.readless2').fadeIn(500);
    })
  })
  $(document).ready(function(){
    $('.readless2').click(function(){
      $('.readmore2').fadeIn(500);
    })
  })
  $(document).ready(function(){
    $('.readless2').click(function(){
      $('.hidden-text2').hide();
    })
  })
  $(document).ready(function(){
    $('.readless2').click(function(){
      $(this).hide();
    })
  })
  
  
  
  $(document).ready(function(){
    $('.readmore3').click(function(){
      $('.hidden-text3').fadeIn(500);
    })
  })
  $(document).ready(function(){
    $('.readmore3').click(function(){
      $(this).hide();
    })
  })
  $(document).ready(function(){
    $('.readmore3').click(function(){
      $('.readless3').fadeIn(500);
    })
  })
  $(document).ready(function(){
    $('.readless3').click(function(){
      $('.readmore3').fadeIn(500);
    })
  })
  $(document).ready(function(){
    $('.readless3').click(function(){
      $('.hidden-text3').hide();
    })
  })
  $(document).ready(function(){
    $('.readless3').click(function(){
      $(this).hide();
    })
  })
  
  
  
  
  $(document).ready(function(){
    $('.readmore4').click(function(){
      $('.hidden-text4').fadeIn(500);
    })
  })
  $(document).ready(function(){
    $('.readmore4').click(function(){
      $(this).hide();
    })
  })
  $(document).ready(function(){
    $('.readmore4').click(function(){
      $('.readless4').fadeIn(500);
    })
  })
  $(document).ready(function(){
    $('.readless4').click(function(){
      $('.readmore4').fadeIn(500);
    })
  })
  $(document).ready(function(){
    $('.readless4').click(function(){
      $('.hidden-text4').hide();
    })
  })
  $(document).ready(function(){
    $('.readless4').click(function(){
      $(this).hide();
    })
  })
